### ISSUE TITLE
Improved design for you.

### ISSUE THREAD

**Issue by GravisZro** [unl-cchil/canine_precise_dispenser#2]
There is actually a _much_ simpler design that would maximize accuracy beyond the current design.  The primary mechanism you should be using is called a [vibratory bowl feeder](https://en.wikipedia.org/wiki/Bowl_feeder) which is deceptively simple but can be used to individually dispense a large number of dog treats of any weight, shape, or size.  [You can 3d print one](https://bytechlab.com/2018/07/smd-parts-bowl-feeder-prototype/) though it's simple enough that the bowl could be cold stamped in your metal of choice.

The downside is that it is slow, so you want a preparatory area that the treat will fall onto.  There are different needs for different experiments, so there should be multiple preparatory area designs.

If you need the ability to rapidly dispense an unknown number of treats until moments before they are dispensed then the preparatory area could be a small conveyor belt.  At the end of the conveyor belt the treats would fall to be dispensed.  How to sense the treat is on the conveyor belt is an exercise left to the reader. ;)

If you know the number of treats to dispense ahead of time then you can just have them fall into a preparatory area with a load cell to count the number of treats.  The preparatory area could actuate like a trap door to dispense the treats.  A simple servo could accomplish this.

**Comment by wsarce** [comment]
Thanks for the feedback!  I agree that there may be better ways to achieve a precise dispenser, I just didn't find any complete open source designs for one intended for the type of research done by Jeff, so I designed one that included everything needed to generate stimulus, take input from a touchscreen, and dispense a precise number of treats.  The diagram for this approach can be found [here](https://github.com/unl-cchil/canine_treat_dispenser/blob/master/documentation/figures/figure2.png), which is a similar setup to what we used for this dispenser, but we did without the embedded system and leveraged the Raspberry Pi.  This was a direct development from our [Treat & Train retrofit dispenser](https://github.com/unl-cchil/canine_treat_dispenser), so we borrowed a lot of ideas from that development.
